[project]
name = "cyclone_cli"
version = "1.0.0"
description = "CLI tool to edit your cyclone DDS config file"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
]

[project.scripts]
cyclonedds = "cyclone_cli.cyclone_cli:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"